#!/bin/sh

echo "Setup Rakitiw"
mm1="/usr/lib/ModemManager/connection.d/10-report-down"
mm2="/usr/lib/ModemManager/connection.d/10-report-down-and-reconnect"

if [ -f "$mm1" ]; then
    rm /usr/lib/ModemManager/connection.d/10-report-down
fi
if [ -f "$mm2" ]; then
    rm /usr/lib/ModemManager/connection.d/10-report-down-and-reconnect
fi

mv "/usr/lib/ModemManager/connection.d/rakitiw" "/usr/lib/ModemManager/connection.d/10-report-down-and-reconnect"
chmod +x /usr/lib/ModemManager/connection.d/10-report-down-and-reconnect

if which pip3 >/dev/null; then
    # Instal paket 'requests' jika belum terinstal
    if ! pip3 show requests >/dev/null; then
        echo "Installing package 'requests'"
        pip3 install requests
    else
        echo "Package 'requests' already installed"
    fi

    # Instal paket 'huawei-lte-api' jika belum terinstal
    if ! pip3 show huawei-lte-api >/dev/null; then
        echo "Installing package 'huawei-lte-api'"
        pip3 install huawei-lte-api
    else
        echo "Package 'huawei-lte-api' already installed"
    fi
else
    echo "Error: 'pip3' command not found"
fi

echo "Setup Done"