#!/bin/bash
# Copyright 2024 RTA SERVER

if chmod +x /usr/bin/rakitanmanager.sh && \
    chmod +x /usr/bin/modem-orbit.py && \
    chmod +x /etc/init.d/rakitiw; then
    echo "Permissions set successfully"
    exit 1
fi