#!/bin/bash
# Copyright 2024 RTA SERVER

sed -i 's/\r$//' /usr/bin/setuprakitiw.sh
sed -i 's/\r$//' /usr/bin/rakitanmanager.sh

chmod 0755 /usr/bin/rakitanmanager.sh
chmod 0755 /usr/bin/setuprakitiw.sh
chmod 0755 /usr/bin/modem-orbit.py
chmod 0755 /etc/init.d/rakitiw